In [71]:
# Numpy 
#  -------------YIELD--------------
# Find Prime Number
from __future__ import print_function
def isPrime(n):
    if n == 1:
        return False
    for t in range(2,n):
        if n%t == 0:
            return False
    return True

def primes(n=1):
    while(n<100):
        if isPrime(n): yield n
        n += 1
for n in primes():
    print (n, end = ' ')   

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [52]:
# fibonacci
def fibo(n):
    i = 0
    j = 1
    for x in range(0,n):
        print (i, end = ' ')
        i, j = j,i + j
fibo(10)

0 1 1 2 3 5 8 13 21 34 

In [53]:
def primes(n=1):
    while n < 100:
        if isPrime(n):print (n, end = ' ')
        n += 1
primes(1)            

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [50]:
[x**3 for x in range(0,6)]

'0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19'

In [54]:
' '.join([`x` for x in range(0,20)])

'0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19'

In [74]:
''.join([str(x) for x in list(range(20))])

'012345678910111213141516171819'

In [75]:
import os
print (os.path.expanduser('~'))

/home/harshil


In [90]:
try:
    with open('filename','r') as f:
        print (f.read())
except IOError:
    print ("No such file exists")

No such file exists


In [87]:
import re
import itertools
print ([x for x in itertools.combinations('123',2)])
print ([x for x in itertools.permutations('123',2)])
re.sub('[aeu]', 'n', re.sub('[abc]', 'o', 'Space'))

[('1', '2'), ('1', '3'), ('2', '3')]
[('1', '2'), ('1', '3'), ('2', '1'), ('2', '3'), ('3', '1'), ('3', '2')]


'Spoon'

In [ ]:
?itertools
?print
?sequence
?linespace
?matrix

In [95]:
import numpy as np
# dir(np)

In [100]:
dup_list = [1,2,3,4,4,4,5,1,2,7,8,8,10]
unique_list = list(set(dup_list))
print (unique_list)

[1, 2, 3, 4, 5, 7, 8, 10]


In [102]:
integers = [ x for x in range(11)]
filter(lambda x: x % 2 == 0, integers)


[0, 2, 4, 6, 8, 10]

In [104]:
map(lambda x: x**2, integers)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [106]:
reduce(lambda x, y: x + y, integers)

55

In [111]:
def print_all(*args):
    for x in enumerate(args):
        print (x)

In [112]:
print_all('A','b','b','a')

(0, 'A')
(1, 'b')
(2, 'b')
(3, 'a')


In [116]:
a = [5,6,7,7,8]

a.remove(7)
print (a)
a.pop()
print (a)
del a[1]
print (a)

[5, 6, 7, 8]
[5, 6, 7]
[5, 7]


In [120]:
s = ['Black', 'holes', 'are', 'where', 'God', 'divided', 'by', 'zero']
print ('\n'.join(s))

Black
holes
are
where
God
divided
by
zero


In [122]:
''.join([str(x) for x in range(0,10)])

'0123456789'

In [145]:
import numpy as np
m = np.matrix([[1,5,3],[5,2,8],[4,7,2]])
n = np.matrix([[3,3,5],[7,2,4],[6,2,3]])
o = np.matrix([[2,6,8],[6,8,3],[9,9,3]])
v = m * 4 
b = m - o
print (m)
# print (n)
print (n)
print (b)

[[1 5 3]
 [5 2 8]
 [4 7 2]]
[[3 3 5]
 [7 2 4]
 [6 2 3]]
[[-1 -1 -5]
 [-1 -6  5]
 [-5 -2 -1]]


In [144]:
f = m * n
print (f)
c = np.multiply(m,n)
print (c)

[[56 19 34]
 [77 35 57]
 [73 30 54]]
[[ 3 15 15]
 [35  4 32]
 [24 14  6]]


In [160]:
#  Question 2
class Car():
    def __init__(self):
        self.brand = ""
        self.maxSpeed = 0
        
    def setBrand(self, brands):
        self.brand = brands
    def setmaxSpeed(self, speed):
        self.maxSpeed = speed
    def printData(self):
        print ("Brand - ",self.brand,"; Max Speed - ",self.maxSpeed)
        
a = Car()
a.setBrand("Audi")
a.setmaxSpeed(230)
a.printData()

b = Car()
b.setBrand("Honda")
b.setmaxSpeed(180)
b.printData()

Brand -  Audi ; Max Speed -  230
Brand -  Honda ; Max Speed -  180
