In [2]:
import numpy as np
print(np.__version__)
#np.__config__.show()

1.10.4


In [12]:
Z = np.zeros(10) 
print Z

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [17]:
P = np.zeros(10)
P[4] = 1
print P

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [57]:
H = np.arange(10,49)
print H[6:-6]
print H[1:-1]
print H[::-1]

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24
 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [62]:
M = np.arange(9).reshape(3,3)
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
nz = np.nonzero([1,2,0,0,4,0])
print nz

(array([0, 1, 4], dtype=int64),)


In [67]:
Z = np.eye(3)
print Z

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [70]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.33940701  0.62284668  0.11156824]
  [ 0.41078952  0.1906071   0.62759238]
  [ 0.43154911  0.73989461  0.83296742]]

 [[ 0.09733218  0.92613152  0.31759582]
  [ 0.98644483  0.33842109  0.93238246]
  [ 0.18399169  0.97948816  0.59043386]]

 [[ 0.64504449  0.9455952   0.53420903]
  [ 0.63761063  0.00500835  0.71674956]
  [ 0.25245847  0.61645774  0.27184638]]]


In [76]:
Z = np.random.random((10,10))
print(Z)
Z.min()
Z.max()

[[ 0.80776224  0.48752065  0.04537304  0.75118187  0.73756142  0.67038886
   0.29468857  0.44593394  0.29815409  0.79355547]
 [ 0.18522993  0.71636819  0.44010813  0.5276584   0.82866781  0.01310597
   0.59527     0.64175263  0.42089515  0.97861843]
 [ 0.82962168  0.45500866  0.56225857  0.37924325  0.09381356  0.31350046
   0.93311536  0.02952337  0.13190889  0.74840683]
 [ 0.79189836  0.36226815  0.8503719   0.2035501   0.72955149  0.11298875
   0.23537491  0.70314085  0.13358662  0.51705592]
 [ 0.49225978  0.54577628  0.83384842  0.8654975   0.042063    0.96192799
   0.5824716   0.42410783  0.31960141  0.52605748]
 [ 0.91085172  0.87536895  0.66496121  0.75608615  0.25966862  0.92958058
   0.62981594  0.45953352  0.00329173  0.03156182]
 [ 0.32244356  0.11420654  0.85865394  0.73151588  0.22347451  0.21843162
   0.82626756  0.55246779  0.84054497  0.00384789]
 [ 0.23885017  0.39873899  0.96053879  0.43590356  0.89341255  0.35529291
   0.45141225  0.91754222  0.86738738  0.34491457]


0.97861843340954668

In [81]:
D = np.random.random(30)
print D
D.mean()

[ 0.44047302  0.81116974  0.1711976   0.19746502  0.20964037  0.53229535
  0.14415024  0.13160239  0.05098626  0.35291712  0.96399502  0.93232814
  0.9228418   0.94829111  0.19390377  0.59356291  0.56577723  0.13729626
  0.17993255  0.97871589  0.00368853  0.24200525  0.56604606  0.64064729
  0.68779813  0.71749121  0.39480424  0.36190906  0.9782902   0.56054845]


0.48705900734600677

In [90]:
F = np.ones((10,10))
F[1:-1,1:-1] = 0
F

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [103]:
0.3 == 3 * 0.1

False

In [120]:
Z = np.diag(1+np.arange(4),k=-1)
Z = np.diag(np.arange(1,5),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [167]:
K = np.zeros((10,10))
K[1::2,::2] = 1
K[::2,1::2] = 1
K

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [169]:
#TILE repeats the values of the array by n 
#a = np.array([0, 1, 2])
#np.tile(a, 2)
#array([0, 1, 2, 0, 1, 2])
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
Z

array([[ 0.62041186,  0.8014094 ,  0.26953938,  0.8429437 ,  0.4403674 ],
       [ 0.67853185,  0.53708312,  0.33368345,  0.28455581,  0.54038007],
       [ 0.36038308,  0.84034763,  0.49604937,  1.        ,  0.54913094],
       [ 0.25430749,  0.845691  ,  0.72594931,  0.        ,  0.11268014],
       [ 0.1018538 ,  0.0359288 ,  0.10044836,  0.31467157,  0.95408702]])

In [34]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [48]:
Z = np.random.random((5,5))
Z
Zmin , Zmax = Z.min(),Z.max()
Z = (Z-Zmin)/(Zmax-Zmin)
Z

array([[ 0.1870763 ,  0.        ,  0.82640601,  0.22328605,  0.2383588 ],
       [ 0.94675387,  0.98337741,  0.61798472,  1.        ,  0.16767373],
       [ 0.81852479,  0.47291043,  0.28852502,  0.6214428 ,  0.30973867],
       [ 0.55546424,  0.48370765,  0.49871181,  0.2451038 ,  0.30214204],
       [ 0.50658173,  0.77064081,  0.31292912,  0.99343007,  0.17829394]])

In [55]:
X = np.ones((5,3))
X
Y = np.ones((3,2))
Y
Z = np.dot(X,Y)
Z
#Z = np.dot(np.ones((5,3)),np.ones((3,2)))

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [56]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [66]:
#xrange(stop) -> xrange object
#xrange(start, stop[, step]) -> xrange object
##fromiter(iterable, dtype, count=-1)
##Create a new 1-dimensional array from an iterable object.

def generate():
    for x in range(5):
        yield x
Z = np.fromiter(generate(),dtype=float,count = -1)
print(Z)


[ 0.  1.  2.  3.  4.]


In [78]:
Z = np.linspace(0,10,12,endpoint = True)[1:-1]
print Z
Z = np.random.random(10)
Z.sort()

[ 0.90909091  1.81818182  2.72727273  3.63636364  4.54545455  5.45454545
  6.36363636  7.27272727  8.18181818  9.09090909]


In [85]:
X = np.random.randint(0,3,5)
Y = np.random.randint(0,3,5)
Z = np.allclose(X,Y)
print Z


False


In [90]:
V = np.zeros(5)
V.flags.writeable = False


In [92]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[ 0.75720859  0.92943409  1.00248622  0.39245121  0.55520098  1.06003449
  0.77220161  0.54463855  0.76453492  0.95162925]
[ 0.47306014  0.81977842  0.29610922  1.55945727  0.93374982  1.13610693
  1.30626671  0.81606487  0.73467178  0.72901388]


In [96]:
Z = np.random.randint(1,5,5)
print Z
print Z.max()
Z[Z.argmax()] = 0
print Z

[1 3 3 1 2]
3
[1 0 3 1 2]


In [115]:
Z = np.arange(20)
V = np.random.uniform(0,20)
print Z,V
index = (np.abs(Z-V)).argmin()
print Z[index]
print Z.argmin(), Z.argmax()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 16.0729493895
16
0 19


In [118]:
#a random vector with shape (100,2) representing coordinates, find point by point distances
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

In [125]:
Z = np.arange(10,dtype = np.int32)
print Z
Z = Z.astype(np.float32, copy = False)
print Z

[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [136]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace = False),1)

In [157]:
D = np.random.uniform(1,10,10)
print D
d = 1
m = D.flat[np.abs(D-d).argmin()]
print m

[ 8.93832385  9.15896806  4.64340294  5.22235406  2.01411222  8.67292388
  3.71960223  2.55524239  4.17836697  8.98034854]
2.01411221915


In [162]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)
?np.bincount

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


In [2]:
import numpy as np 
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


In [14]:
lists = range(0,10,2)
print lists
for i in lists:
    assert i%2==0
exp = raw_input()
print eval(exp)

[0, 2, 4, 6, 8]
23+90
113


In [21]:
li = [2,4,6,9,12,23,34,55,65]
def binsearch(ele,lists):
    top = len(lists) - 1
    bottom = 0
    index = -1
    while bottom<=top and index == -1:
        mid = int(top+bottom)/2
        if lists[mid]==ele:
            index = mid
        elif lists[mid]>ele:
            top = mid -1
        else:
            bottom = mid + 1
    return index
print binsearch(34,li)


6


In [112]:
import random
h = np.random.random()*100
print h
print np.random.choice([x for x in range(0,10) if x%2==0])
print np.random.choice([x for x in range(0,100) if x%5==0 and x%7==0])
print random.sample([x for x in range(100,200) if x %2==0],5)
print random.randrange(5,17)

99.7935441304
6
70
[180, 154, 198, 130, 190]
12


In [114]:
import zlib
s = 'hello world!hello world!hello world!hello world!'
t = zlib.compress(s)
print t
print zlib.decompress(t)

�[�
hello world!hello world!hello world!hello world!


In [116]:
from timeit import Timer
t = Timer("for i in range(100):1+1")
print t.timeit()

2.76416449857


In [120]:
from random import shuffle
li = [3,6,7,8]
shuffle(li)
print li

[6, 8, 7, 3]


In [122]:
li = [12,24,35,70,88,120,155]
li = [x for (i,x) in enumerate(li) if i%2!=0]
print li

[24, 70, 120]


In [130]:
mat = np.zeros((3,5))
array = [[[0 for col in range(8)] for col in range(5)] for row in range(3)]
print array

[[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]]


In [135]:
array =  [12,24,35,70,88,120,155]
arr = [x for (i,x) in enumerate(array) if i not in (0,4,5)]
arr
lists =  [12,24,35,70,88,120,155]
li = [x for x in lists if x!=24]


In [140]:
set1  =  set([1,3,6,78,35,55])
set2 = set([12,24,35,24,88,120,155])
set1 &= set2
li=list(set1)
print li

[35]


In [142]:
set1 = set([12,24,35,24,88,120,155,88,120,155])
print set1

set([35, 12, 88, 24, 120, 155])


In [155]:
class person(object):
    def getGender(self):
        return "unknown"
class Male(person):
    def getGender(self):
        return "male"
class Female(person):
    def getGender(self):
        return "female"
        
f = Female()
f.getGender() 

'female'

In [159]:
s = raw_input()
dic = {}
for s in s:
    dic[s] = dic.get(s,0) + 1
print '\n'.join(['%s,%s' %(k,v) for k,v in dic.items()])

alsjdflweor
a,1
e,1
d,1
f,1
j,1
l,2
o,1
s,1
r,1
w,1


In [164]:
s = raw_input()
print s[::-1]
print s[::2]

harshil
lihsrah
hrhl


In [167]:
import itertools
print list(itertools.permutations([1,2,3]))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [183]:
import re
emailAddress = raw_input()
pat2 = "(\w+)@((\w+\.)+(com))"
r2 = re.match(pat2,emailAddress)
print r2.group(2)

harhil@fl.com
fl.com
